// vue-drag-drop/src/components/Board.vue
<template>
    <div
        :id="id"
        class="board"
        @dragover.prevent
        @drop.prevent='drop'
    >
        <slot/>
    </div>
</template>


<script>
export default {
    props:["id"],
    methods:{
        drop:e=>{
            const card_id=e.dataTransfer.getData("card_id");

            const card=document.getElementById(card_id);

            card.style.display="block";
            e.target.appendChild(card);
        }
    }
}
</script>

// drag-drop-react/src/components/Board.js

import React from 'react';

function Board(props) {

    const drop = e=>{
        console.log(e);
        e.preventDefault();
        const card_id=e.dataTransfer.getData('card_id');

        const card=document.getElementById('card_id');
        card.style.display="block";

        e.target.appendChild(card);

    }

    const dragOver=e=>{
        e.preventDefault();
    }
    return (
        <div
            id={props.id}
            className={props.className}
            onDrop={drop}
            onDragOver={dragOver}
        >
            {props.children}
        </div>
    )
}

export default Board;
