// vue-drag-drop/src/components/Card.vue
<template>
    <div
        :id="id"
        class="card"
        :draggable="draggable"
        @dragstart="dragStart"
        @dragover.stop
        @drop.prevent='drop'
    >
        <slot/>
    </div>
</template>


<script>
export default {
    props:["id","draggable"],
    methods:{
        dragStart:e=>{
            const target=e.target;
            e.dataTransfer.setData("card_id",target.id);

            setTimeout(()=>{
                target.style.display="none";
            },0)

            
        }
    }
}
</script>

// drag-drop-react/src/components/Card.js

import React from 'react';

function Card(props) {

    const dragStart=e=>{
        const target=e.target;

        e.dataTransfer.setData("card_id",target.id)

        setTimeout(()=>{
            target.style.display="none"
        },0)
    }

    const dragOver=e=>{
        e.stopPropogation();
    }
    return (
        <div
            id={props.id}
            className={props.className}
            draggable={props.draggable}
            onDragStart={dragStart}
            onDragOver={dragOver}
        >
          {props.children}  
        </div>
    )
}

export default Card;
